export type PhotoSpot = {
  id: string;
  name: string;
  city: string;
  zone: string;
  description: string;
  tags: string[];
  image: string;
  tip: string;
  access: string;
  address: string;
};

export const zones = [
  'Tous',
  'Paris (75)',
  'Hauts-de-Seine (92)',
  'Val-de-Marne (94)',
  'Seine-et-Marne (77)',
  'Yvelines (78)',
  "Val-d'Oise (95)",
  'Essonne (91)',
  'Seine-Saint-Denis (93)',
];

export const tagsList = [
  { id: 'tous', label: 'Tous' },
  { id: 'portrait', label: 'Portrait' },
  { id: 'couple', label: 'Couple' },
  { id: 'mode', label: 'Mode' },
  { id: 'nature', label: 'Nature' },
  { id: 'architecture', label: 'Architecture' },
  { id: 'street', label: 'Street' },
  { id: 'animal', label: 'Animal' },
];

export const photoSpots: PhotoSpot[] = [
  // ─── PARIS (75) ───────────────────────────────────────────────────────────
  {
    id: 'palais-royal',
    name: 'Jardins du Palais-Royal',
    city: 'Paris 1er',
    zone: 'Paris (75)',
    description: 'Colonnes de Buren, galeries et jardins géométriques. Palette architecturale unique idéale pour la mode et les portraits artistiques.',
    tags: ['portrait', 'mode', 'architecture'],
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6c/Colonnes_Buren_Cour_Honneur_Palais_Royal_Paris_1.jpg/500px-Colonnes_Buren_Cour_Honneur_Palais_Royal_Paris_1.jpg',
    tip: 'Tôt le matin avant 9h : le lieu est quasi-vide. Colonnes de Buren en longue exposition.',
    access: 'M° Palais Royal — Musée du Louvre',
    address: 'Place du Palais-Royal, 75001 Paris',
  },
  {
    id: 'canal-saint-martin',
    name: 'Canal Saint-Martin',
    city: 'Paris 10e',
    zone: 'Paris (75)',
    description: 'Ponts en fonte, écluses et façades colorées. Ambiance bohème idéale pour les portraits lifestyle et les couples.',
    tags: ['portrait', 'couple', 'street'],
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/Canal_Saint-Martin_P1060441.JPG/500px-Canal_Saint-Martin_P1060441.JPG',
    tip: "Golden hour en fin d'après-midi pour une lumière chaude sur l'eau des écluses.",
    access: 'M° République ou Jacques Bonsergent',
    address: 'Quai de Valmy, 75010 Paris',
  },
  {
    id: 'buttes-chaumont',
    name: 'Parc des Buttes-Chaumont',
    city: 'Paris 19e',
    zone: 'Paris (75)',
    description: 'Collines, lac, temple de la Sibylle en surplomb. Parc le plus photogénique de Paris pour portraits en pleine nature.',
    tags: ['portrait', 'couple', 'nature'],
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c8/Parc_des_Buttes-Chaumont%2C_temple_de_la_Sybille_05.jpg/500px-Parc_des_Buttes-Chaumont%2C_temple_de_la_Sybille_05.jpg',
    tip: "Temple sur l'île offre un cadre unique. Y accéder tôt le matin pour éviter la foule du week-end.",
    access: 'M° Buttes Chaumont ou Botzaris',
    address: '1 Rue Botzaris, 75019 Paris',
  },
  {
    id: 'trocadero',
    name: 'Trocadéro & Champ-de-Mars',
    city: 'Paris 16e / 7e',
    zone: 'Paris (75)',
    description: 'Vue emblématique sur la Tour Eiffel. Incontournable pour toutes les sessions avec une touche parisienne iconique.',
    tags: ['portrait', 'couple', 'architecture'],
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/34/La_tour_Eiffel_vue_du_Trocad%C3%A9ro.JPG/500px-La_tour_Eiffel_vue_du_Trocad%C3%A9ro.JPG',
    tip: 'Heure bleue (20 min après coucher du soleil) pour la Tour Eiffel illuminée. Lever du soleil côté Champ-de-Mars pour la lumière dorée.',
    access: 'M° Trocadéro ou Bir-Hakeim',
    address: 'Place du Trocadéro et du 11 Novembre, 75016 Paris',
  },
  {
    id: 'montmartre',
    name: 'Montmartre & Sacré-Cœur',
    city: 'Paris 18e',
    zone: 'Paris (75)',
    description: 'Rues pavées, escaliers romantiques, vue panoramique sur Paris. Ambiance village artistique incomparable.',
    tags: ['portrait', 'couple', 'street', 'architecture'],
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e7/Sacr%C3%A9-C%C5%93ur_Montmartre_Paris_France.JPG/500px-Sacr%C3%A9-C%C5%93ur_Montmartre_Paris_France.JPG',
    tip: 'Éviter le week-end midi. Ruelle Lepic et place des Abbesses sont plus calmes que les abords du Sacré-Cœur.',
    access: 'M° Abbesses ou Lamarck — Caulaincourt',
    address: 'Place du Parvis du Sacré-Cœur, 75018 Paris',
  },
  {
    id: 'pont-alexandre',
    name: 'Pont Alexandre III',
    city: 'Paris 8e',
    zone: 'Paris (75)',
    description: 'Le pont le plus orné de Paris. Lampadaires dorés, chérubins et vue sur les Invalides. Idéal pour la mode et les couples.',
    tags: ['portrait', 'couple', 'mode', 'architecture'],
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/89/Le_pont_Alexandre_III%2C_Alexander_III_bridge_Paris_7.JPG/500px-Le_pont_Alexandre_III%2C_Alexander_III_bridge_Paris_7.JPG',
    tip: 'Lumière dorée en fin de journée sur les ornements du pont. Tôt le matin pour éviter les voitures.',
    access: "M° Invalides ou Champs-Élysées — Clemenceau",
    address: 'Pont Alexandre III, 75007 Paris',
  },
  {
    id: 'parc-monceau',
    name: 'Parc Monceau',
    city: 'Paris 8e',
    zone: 'Paris (75)',
    description: "Jardin romantique avec colonnade, rotonde et statues. Couleurs d'automne exceptionnelles. Très apprécié pour les portraits.",
    tags: ['portrait', 'couple', 'nature'],
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Parc_Monceau_Paris_8e_005.JPG/500px-Parc_Monceau_Paris_8e_005.JPG',
    tip: "Octobre-novembre pour les couleurs automnales autour de la colonnade antique.",
    access: 'M° Monceau',
    address: '35 Boulevard de Courcelles, 75008 Paris',
  },
  {
    id: 'ile-saint-louis',
    name: 'Île Saint-Louis & Île de la Cité',
    city: 'Paris 4e',
    zone: 'Paris (75)',
    description: "Hôtels particuliers du XVIIe, quais tranquilles, vue sur Notre-Dame. Atmosphère hors du temps.",
    tags: ['portrait', 'couple', 'architecture', 'street'],
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/11/Ile_Saint-Louis_Paris_4e_001.JPG/500px-Ile_Saint-Louis_Paris_4e_001.JPG',
    tip: "Quais bas (côté eau) pour un cadre intimiste. Lumière magnifique en soirée depuis le Pont de la Tournelle.",
    access: 'M° Sully — Morland ou Pont Marie',
    address: "Quai d'Anjou, 75004 Paris",
  },
  {
    id: 'jardin-luxembourg',
    name: 'Jardin du Luxembourg',
    city: 'Paris 6e',
    zone: 'Paris (75)',
    description: "Palais, bassins, statues et orangerie entourés de marronniers centenaires. L'un des plus beaux jardins parisiens, prisé pour les portraits bourgeois et romantiques.",
    tags: ['portrait', 'couple', 'nature', 'architecture'],
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/16/Jardin_du_Luxembourg.JPG/500px-Jardin_du_Luxembourg.JPG',
    tip: "Grand bassin central pour des portraits avec le Palais en fond. Allées d'arbres idéales en automne.",
    access: 'M° Odéon ou RER B — Luxembourg',
    address: 'Rue de Médicis, 75006 Paris',
  },
  {
    id: 'bois-boulogne',
    name: 'Bois de Boulogne',
    city: 'Paris 16e',
    zone: 'Paris (75)',
    description: 'Forêt en plein Paris avec lacs, jardins et allées cavalières. Parfait pour animaux, portraits nature et famille.',
    tags: ['portrait', 'animal', 'nature'],
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Lac_du_bois_de_Boulogne.JPG/500px-Lac_du_bois_de_Boulogne.JPG',
    tip: "Jardin de Bagatelle pour les roses (mai-juin) ou Pré Catelan pour les prairies dégagées.",
    access: "M° Porte Dauphine ou Porte d'Auteuil",
    address: 'Route de Suresnes, 75016 Paris',
  },
  {
    id: 'villette',
    name: 'Parc de la Villette',
    city: 'Paris 19e',
    zone: 'Paris (75)',
    description: 'Espace contemporain avec Géode, folies rouges et grandes prairies. Architecture moderne et lignes graphiques.',
    tags: ['portrait', 'mode', 'architecture', 'street'],
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7c/City_of_Sciences_La_Villette_Paris_images_of_reflections_on_the_Geode_2.jpg/500px-City_of_Sciences_La_Villette_Paris_images_of_reflections_on_the_Geode_2.jpg',
    tip: 'Les folies rouges et la Géode créent des reflets et contrastes très graphiques. Idéal pour la mode.',
    access: 'M° Porte de la Villette ou Corentin Cariou',
    address: '211 Avenue Jean Jaurès, 75019 Paris',
  },
  {
    id: 'pere-lachaise',
    name: 'Cimetière du Père-Lachaise',
    city: 'Paris 20e',
    zone: 'Paris (75)',
    description: "Allées bordées de tombeaux sculptés, chapelles néo-gothiques et végétation dense. Atmosphère romantique et mystérieuse unique à Paris.",
    tags: ['portrait', 'mode', 'architecture', 'street'],
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Paris_P%C3%A8re-Lachaise_006.JPG/500px-Paris_P%C3%A8re-Lachaise_006.JPG',
    tip: "Tombeaux de Chopin, Oscar Wilde et Édith Piaf : cadres cinématographiques. Lumière filtrée à travers les arbres en été.",
    access: 'M° Père Lachaise ou Philippe Auguste',
    address: '16 Rue du Repos, 75020 Paris',
  },

  // ─── HAUTS-DE-SEINE (92) ──────────────────────────────────────────────────
  {
    id: 'sceaux',
    name: 'Parc de Sceaux',
    city: 'Sceaux',
    zone: 'Hauts-de-Seine (92)',
    description: "Jardins à la française inspirés de Versailles avec bassins géométriques et cerisiers en fleur au printemps.",
    tags: ['portrait', 'couple', 'architecture', 'nature'],
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/87/Cerisiers_en_fleurs_au_parc_de_Sceaux.JPG/500px-Cerisiers_en_fleurs_au_parc_de_Sceaux.JPG',
    tip: "Fin mars–début avril pour les cerisiers (hanami) : un spectacle unique en Île-de-France.",
    access: 'RER B — Robinson ou Parc de Sceaux',
    address: 'Avenue du Président Wilson, 92330 Sceaux',
  },
  {
    id: 'la-defense',
    name: 'La Défense & Grande Arche',
    city: 'Puteaux / Courbevoie',
    zone: 'Hauts-de-Seine (92)',
    description: 'Skyline de tours, Grande Arche et esplanade piétonne. Architecture futuriste et lignes de fuite impressionnantes.',
    tags: ['portrait', 'mode', 'architecture'],
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1f/Grande_Arche%2C_France_-_April_2011.jpg/500px-Grande_Arche%2C_France_-_April_2011.jpg',
    tip: "Tôt le matin en semaine pour l'esplanade vide. Reflets dans les tours vitrées spectaculaires.",
    access: 'M° ou RER A — La Défense',
    address: '1 Parvis de la Défense, 92800 Puteaux',
  },
  {
    id: 'saint-cloud',
    name: 'Parc de Saint-Cloud',
    city: 'Saint-Cloud',
    zone: 'Hauts-de-Seine (92)',
    description: "Immense parc royal en surplomb de la Seine. Grandes cascades, bassins et perspectives royales avec vue imprenable sur Paris.",
    tags: ['portrait', 'couple', 'nature', 'architecture'],
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/50/Parc-St-Cloud_04.JPG/500px-Parc-St-Cloud_04.JPG',
    tip: "Grande Cascade active certains dimanches en saison. Rond-point de la Balustrade pour la vue Paris.",
    access: 'Transilien L — Saint-Cloud ou bus depuis M° Pont-de-Sèvres',
    address: '2 Rue de Marnes, 92210 Saint-Cloud',
  },
  {
    id: 'boulogne-billancourt',
    name: 'Château Rothschild & Jardins',
    city: 'Boulogne-Billancourt',
    zone: 'Hauts-de-Seine (92)',
    description: "Domaine bourgeois du XIXe au cœur de Boulogne. Parc paysager anglais, façade néo-Renaissance et perspectives arborées dans un cadre aristocratique discret.",
    tags: ['portrait', 'couple', 'mode', 'architecture'],
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b9/Ch%C3%A2teau_Rothschild_%C3%A0_Boulogne-Billancourt_002.JPG/500px-Ch%C3%A2teau_Rothschild_%C3%A0_Boulogne-Billancourt_002.JPG',
    tip: "Façade côté jardin pour un cadre élégant. Allées dégagées très propices aux portraits mode en semaine.",
    access: 'M° Boulogne — Jean Jaurès',
    address: '60 Route de la Reine, 92100 Boulogne-Billancourt',
  },
  {
    id: 'meudon',
    name: 'Terrasse & Forêt de Meudon',
    city: 'Meudon',
    zone: 'Hauts-de-Seine (92)',
    description: 'Vue panoramique sur Paris et la vallée de la Seine. Forêt dense pour des portraits en sous-bois.',
    tags: ['portrait', 'nature', 'couple'],
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/04/Vue_de_Paris_depuis_Meudon.jpg/500px-Vue_de_Paris_depuis_Meudon.jpg',
    tip: "Sous-bois de la forêt de Meudon : lumière filtrée excellente. Terrasse pour la vue Paris en contre-plongée.",
    access: 'Transilien N — Bellevue ou Meudon',
    address: 'Terrasse de Bellevue, 92190 Meudon',
  },
  {
    id: 'ile-saint-germain',
    name: 'Île Saint-Germain',
    city: 'Issy-les-Moulineaux',
    zone: 'Hauts-de-Seine (92)',
    description: "Île aménagée sur la Seine avec sculptures monumentales, jardin calme et vue sur Paris. Peu connue des photographes.",
    tags: ['portrait', 'couple', 'nature', 'street'],
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e2/%C3%8Ele_Saint-Germain_001.JPG/500px-%C3%8Ele_Saint-Germain_001.JPG',
    tip: "Sculptures géantes de Jaume Plensa : cadres originaux pour la mode et le portrait artistique.",
    access: 'M° Corentin Celton',
    address: 'Allée des Hérons, 92130 Issy-les-Moulineaux',
  },

  // ─── VAL-DE-MARNE (94) ────────────────────────────────────────────────────
  {
    id: 'vincennes',
    name: 'Château & Bois de Vincennes',
    city: 'Vincennes',
    zone: 'Val-de-Marne (94)',
    description: "Château médiéval royal avec donjon, Sainte-Chapelle gothique et fossés. Plus grand bois de la région parisienne avec lacs et vastes prairies.",
    tags: ['portrait', 'couple', 'animal', 'nature', 'architecture'],
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e4/Chateau_de_Vincennes_%28pixinn.net%29.jpg/500px-Chateau_de_Vincennes_%28pixinn.net%29.jpg',
    tip: "Lac Daumesnil pour des reflets sur l'eau. Forêt de châtaigniers spectaculaire en automne (octobre).",
    access: 'M° Château de Vincennes',
    address: 'Avenue de Paris, 94300 Vincennes',
  },
  {
    id: 'maisons-alfort',
    name: 'Bords de Marne — Guinguettes',
    city: 'Maisons-Alfort / Joinville-le-Pont',
    zone: 'Val-de-Marne (94)',
    description: "Guinguettes, berges ombragées et ponts en bois. Ambiance vintage et champêtre à 15 min de Paris.",
    tags: ['portrait', 'couple', 'nature', 'street'],
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/Quai_Marne_-_Joinville-le-Pont_%28FR94%29_-_2021-02-04_-_1.jpg/500px-Quai_Marne_-_Joinville-le-Pont_%28FR94%29_-_2021-02-04_-_1.jpg',
    tip: "Guinguettes de Joinville-le-Pont pour une ambiance 1920s. Lumière dorée sur la Marne en soirée.",
    access: 'RER A — Joinville-le-Pont',
    address: 'Quai Victor Hugo, 94340 Joinville-le-Pont',
  },
  {
    id: 'creteil-lac',
    name: 'Lac de Créteil',
    city: 'Créteil',
    zone: 'Val-de-Marne (94)',
    description: "Grand lac artificiel entouré de prairies et de berges aménagées. Reflets sur l'eau, voiliers et centre aquatique en fond. Idéal pour des portraits nature en banlieue.",
    tags: ['portrait', 'couple', 'nature'],
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/Lac_de_Cr%C3%A9teil_01.jpg/500px-Lac_de_Cr%C3%A9teil_01.jpg',
    tip: "Tour du lac en golden hour pour les reflets sur l'eau. Côté prairie pour des portraits dégagés.",
    access: "M° Créteil — L'Échat ou Créteil — Préfecture",
    address: 'Avenue du Lac, 94000 Créteil',
  },
  {
    id: 'nogent-marne',
    name: 'Pavillon Baltard & Bords de Marne',
    city: 'Nogent-sur-Marne',
    zone: 'Val-de-Marne (94)',
    description: "Pavillon des Halles de Paris réinstallé en 1976 : charpente métallique du XIXe unique. Berges de la Marne ombragées et guinguettes pour un mix patrimoine et champêtre.",
    tags: ['portrait', 'couple', 'architecture', 'nature'],
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Nogent-sur-Marne_Pavillon_Baltard.jpg/500px-Nogent-sur-Marne_Pavillon_Baltard.jpg',
    tip: "Charpente métallique du Pavillon : lumière zénithale superbe en milieu de matinée. Berges très calmes en semaine.",
    access: 'RER A — Nogent-sur-Marne',
    address: 'Parc du Rancy, 94130 Nogent-sur-Marne',
  },

  // ─── SEINE-ET-MARNE (77) ──────────────────────────────────────────────────
  {
    id: 'fontainebleau-foret',
    name: 'Forêt de Fontainebleau',
    city: 'Fontainebleau',
    zone: 'Seine-et-Marne (77)',
    description: "Massif rocheux spectaculaire, châtaigniers centenaires, chaos granitiques. Cadre sauvage unique en Île-de-France.",
    tags: ['portrait', 'animal', 'nature', 'couple'],
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/18/Rochers_en_for%C3%AAt_de_Fontainebleau11.JPG/500px-Rochers_en_for%C3%AAt_de_Fontainebleau11.JPG',
    tip: "Gorges de Franchard et Gorges d'Apremont pour les rochers. Automne exceptionnel fin octobre.",
    access: 'Transilien R — Fontainebleau-Avon',
    address: 'Route des Gorges de Franchard, 77300 Fontainebleau',
  },
  {
    id: 'fontainebleau-chateau',
    name: 'Château de Fontainebleau',
    city: 'Fontainebleau',
    zone: 'Seine-et-Marne (77)',
    description: "Résidence royale Renaissance. Jardins à la française, cour des Adieux et Grand Parterre. Élégance absolue.",
    tags: ['portrait', 'couple', 'mode', 'architecture'],
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ab/Chateau_de_Fontainebleau_FRA_007.JPG/500px-Chateau_de_Fontainebleau_FRA_007.JPG',
    tip: "Galeries extérieures parfaites les jours couverts. Grand Canal pour les portraits avec reflets.",
    access: 'Transilien R — Fontainebleau-Avon + 15 min à pied',
    address: 'Place du Général de Gaulle, 77300 Fontainebleau',
  },
  {
    id: 'vaux-le-vicomte',
    name: 'Château de Vaux-le-Vicomte',
    city: 'Maincy',
    zone: 'Seine-et-Marne (77)',
    description: "Le plus beau château de France avant Versailles. Jardins de Le Nôtre et perspectives spectaculaires à perte de vue.",
    tags: ['portrait', 'couple', 'mode', 'architecture'],
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2d/0_Maincy_-_Ch%C3%A2teau_de_Vaux-le-Vicomte_%281%29.JPG/500px-0_Maincy_-_Ch%C3%A2teau_de_Vaux-le-Vicomte_%281%29.JPG',
    tip: "Entrée payante (ticket photo parfois requis). Soirées aux chandelles le samedi soir en saison.",
    access: "Transilien P — Verneuil l'Étang + taxi/voiture",
    address: 'Château de Vaux-le-Vicomte, 77950 Maincy',
  },
  {
    id: 'provins',
    name: 'Cité médiévale de Provins',
    city: 'Provins',
    zone: 'Seine-et-Marne (77)',
    description: "Ville médiévale classée UNESCO. Remparts du XIIe, Tour César, ruelles pavées et caves troglodytes. Décor de série historique à 1h30 de Paris.",
    tags: ['portrait', 'couple', 'architecture', 'street'],
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Medieval_fortifications_of_Provins_P1120608.JPG/500px-Medieval_fortifications_of_Provins_P1120608.JPG',
    tip: "Remparts dégagés tôt le matin avant les groupes de touristes. Tour César pour la vue panoramique sur la plaine.",
    access: 'Transilien P — Provins',
    address: 'Place du Châtel, 77160 Provins',
  },
  {
    id: 'moret-sur-loing',
    name: 'Moret-sur-Loing',
    city: 'Moret-sur-Loing',
    zone: 'Seine-et-Marne (77)',
    description: "Village médiéval peint par Sisley. Porte de Bourgogne, pont du XIIe, moulins et rivière transparente. Carte postale en pleine nature à 75 km de Paris.",
    tags: ['portrait', 'couple', 'architecture', 'nature'],
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/86/Moret-sur-Loing_%2877%29%2C_porte_de_Bourgogne_1.JPG/500px-Moret-sur-Loing_%2877%29%2C_porte_de_Bourgogne_1.JPG',
    tip: "Pont médiéval avec le village en fond : scène impressionniste parfaite. Lever du soleil sur le Loing en été.",
    access: "Transilien R — Moret — Veneux-les-Sablons",
    address: 'Rue Grande, 77250 Moret-sur-Loing',
  },

  // ─── YVELINES (78) ────────────────────────────────────────────────────────
  {
    id: 'versailles-jardins',
    name: 'Jardins du Château de Versailles',
    city: 'Versailles',
    zone: 'Yvelines (78)',
    description: "Jardins de Le Nôtre, Grand Canal, bosquets et fontaines. Grandeur royale absolue pour des portraits aristocratiques.",
    tags: ['portrait', 'couple', 'mode', 'architecture'],
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/24/Grand_Canal_de_Versailles.jpg/500px-Grand_Canal_de_Versailles.jpg',
    tip: "Accès jardins gratuit hors Grandes Eaux. Tôt le matin pour des allées vides. Orangerie en contre-jour.",
    access: 'RER C — Versailles Château Rive Gauche',
    address: "Place d'Armes, 78000 Versailles",
  },
  {
    id: 'saint-germain-en-laye',
    name: 'Château & Terrasse de Saint-Germain-en-Laye',
    city: 'Saint-Germain-en-Laye',
    zone: 'Yvelines (78)',
    description: "Château royal renaissance et terrasse du Nôtre longue de 2,4 km avec vue sur la Seine et Paris au loin. Forêt royale de 3500 ha pour des sous-bois épais en toutes saisons.",
    tags: ['portrait', 'animal', 'nature', 'couple', 'architecture'],
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1c/Chateau_de_St_Germain-en-laye.JPG/500px-Chateau_de_St_Germain-en-laye.JPG',
    tip: "Terrasse du Château pour la vue Paris en fond. Sous-bois très denses pour une lumière tamisée.",
    access: 'RER A — Saint-Germain-en-Laye',
    address: 'Place Charles de Gaulle, 78100 Saint-Germain-en-Laye',
  },
  {
    id: 'rambouillet',
    name: 'Château & Forêt de Rambouillet',
    city: 'Rambouillet',
    zone: 'Yvelines (78)',
    description: "Château présidentiel entouré d'une immense forêt avec lacs, bergerie nationale et parc. Daims et cerfs pour la photo animalière.",
    tags: ['animal', 'nature', 'portrait'],
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ed/Ch%C3%A2teau_de_Rambouillet_2013.JPG/500px-Ch%C3%A2teau_de_Rambouillet_2013.JPG',
    tip: "Étangs de la Ménagerie pour la faune sauvage. Bergerie nationale pour un cadre champêtre authentique.",
    access: 'Transilien N — Rambouillet',
    address: '1 Place de la Libération, 78120 Rambouillet',
  },
  {
    id: 'poissy',
    name: 'Villa Savoye — Le Corbusier',
    city: 'Poissy',
    zone: 'Yvelines (78)',
    description: "Chef-d'œuvre du mouvement moderne (1929) classé monument historique. Lignes pures, pilotis et toit-jardin : architecture sculptée idéale pour la mode et le portrait contemporain.",
    tags: ['portrait', 'mode', 'architecture'],
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ee/Villa_Savoye_%288237925975%29.jpg/500px-Villa_Savoye_%288237925975%29.jpg',
    tip: "Façade sud en contre-jour en fin d'après-midi. Pilotis et rampe hélicoïdale : cadres très graphiques pour la mode.",
    access: 'Transilien L — Poissy, 20 min à pied ou bus C1',
    address: '82 Rue de Villiers, 78300 Poissy',
  },

  // ─── VAL-D'OISE (95) ──────────────────────────────────────────────────────
  {
    id: 'enghien',
    name: "Lac d'Enghien-les-Bains",
    city: 'Enghien-les-Bains',
    zone: "Val-d'Oise (95)",
    description: "Unique lac naturel en Île-de-France. Casino Belle Époque, villas cossues et promenades lacustres.",
    tags: ['portrait', 'couple', 'architecture'],
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/71/Enghien-les-Bains_-_Front_du_lac_-_panoramique.jpg/500px-Enghien-les-Bains_-_Front_du_lac_-_panoramique.jpg',
    tip: "Tour du lac en début de matinée. Bâtiments Art déco et casino en arrière-plan.",
    access: 'Transilien H — Enghien-les-Bains',
    address: "Allée du Lac, 95880 Enghien-les-Bains",
  },
  {
    id: 'auvers-sur-oise',
    name: "Église Notre-Dame — Van Gogh",
    city: "Auvers-sur-Oise",
    zone: "Val-d'Oise (95)",
    description: "Village immortalisé par Van Gogh. Église gothique peinte dans ses dernières toiles, champs de blé, auberge Ravoux et tombes des frères Van Gogh. Atmosphère impressionniste unique.",
    tags: ['portrait', 'couple', 'architecture', 'nature'],
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/00/Eglise_auvers.JPG/500px-Eglise_auvers.JPG',
    tip: "Recréer exactement le point de vue de Van Gogh devant l'église (panneau indiqué in situ). Champs en été pour les portraits en plein air.",
    access: "Transilien H — Auvers-sur-Oise",
    address: "Place de l'Église, 95430 Auvers-sur-Oise",
  },
  {
    id: 'isle-adam',
    name: "L'Isle-Adam — Bords de l'Oise",
    city: "L'Isle-Adam",
    zone: "Val-d'Oise (95)",
    description: "Ville fluviale avec plage, forêt et vieilles rues. Berges de l'Oise champêtres à 45 min de Paris.",
    tags: ['portrait', 'couple', 'nature', 'street'],
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d8/L%27Isle-Adam_-_Plage_vue_de_la_passerelle.jpg/500px-L%27Isle-Adam_-_Plage_vue_de_la_passerelle.jpg',
    tip: "Plage en contre-saison totalement déserte. Berges de l'Oise pour des portraits champêtres.",
    access: "Transilien H — L'Isle-Adam — Parmain",
    address: "Plage de L'Isle-Adam, 95290 L'Isle-Adam",
  },
  {
    id: 'royaumont',
    name: "Abbaye de Royaumont",
    city: "Asnières-sur-Oise",
    zone: "Val-d'Oise (95)",
    description: "Une des plus belles abbayes gothiques de France (1228). Cloître, réfectoire des moines et jardins en eau dans un cadre de silence absolu. Lieu de séances photo exceptionnel.",
    tags: ['portrait', 'couple', 'architecture', 'mode'],
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/97/Abbaye_de_Royaumont_w1.jpg/500px-Abbaye_de_Royaumont_w1.jpg',
    tip: "Cloître intérieur : lumière dorée en fin de matinée traversant les arches. Jardins en eau parfaits pour les couples.",
    access: "Voiture depuis Paris — 40 min (pas de transport direct proche)",
    address: "Route de Royaumont, 95270 Asnières-sur-Oise",
  },
  {
    id: 'pontoise',
    name: 'Axe Majeur de Cergy & Vieux Pontoise',
    city: 'Pontoise / Cergy',
    zone: "Val-d'Oise (95)",
    description: "Ruelles médiévales de Pontoise peintes par Pissarro et architecture contemporaine de l'Axe Majeur de Cergy. Deux ambiances contrastées à explorer.",
    tags: ['portrait', 'architecture', 'street'],
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/Axe_majeur_de_Cergy_P1090788.JPG/500px-Axe_majeur_de_Cergy_P1090788.JPG',
    tip: "Axe majeur de Cergy pour les lignes de fuite. Centre historique de Pontoise pour l'ambiance médiévale et impressionniste.",
    access: 'RER A — Cergy ou Pontoise',
    address: "Belvédère de l'Axe Majeur, 95800 Cergy",
  },

  // ─── ESSONNE (91) ─────────────────────────────────────────────────────────
  {
    id: 'foret-senart',
    name: 'Forêt de Sénart',
    city: 'Tigery / Lieusaint',
    zone: 'Essonne (91)',
    description: 'Grande forêt de 3 500 ha avec allées cavalières, étangs et sous-bois denses. Calme et lumière filtrée à 30 min de Paris.',
    tags: ['portrait', 'animal', 'nature', 'couple'],
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b5/For%C3%AAt_de_S%C3%A9nart_-_Jonquilles.jpg/500px-For%C3%AAt_de_S%C3%A9nart_-_Jonquilles.jpg',
    tip: "Étang de la Grange-aux-Ormes pour des portraits avec reflets sur l'eau. Automne très coloré en octobre.",
    access: 'RER D — Lieusaint — Moissy',
    address: 'Route de Lyon, 91250 Tigery',
  },
  {
    id: 'chevreuse',
    name: 'Vallée de Chevreuse',
    city: 'Saint-Rémy-lès-Chevreuse',
    zone: 'Essonne (91)',
    description: "Vallée verdoyante avec moulins, prairies fleuries et abbaye de Port-Royal. Campagne authentique à 30 km de Paris.",
    tags: ['portrait', 'couple', 'animal', 'nature'],
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e2/Abbey_of_Port-Royal%2C_General_View_by_Louise-Magdeleine_Horthemels_c._1710.jpg/500px-Abbey_of_Port-Royal%2C_General_View_by_Louise-Magdeleine_Horthemels_c._1710.jpg',
    tip: "Abbaye de Port-Royal en arrière-plan pour un cadre patrimonial sobre. Idéal au printemps avec les fleurs des prairies.",
    access: 'RER B — Saint-Rémy-lès-Chevreuse',
    address: 'Abbaye de Port-Royal, 78114 Magny-les-Hameaux',
  },
  {
    id: 'caillebotte',
    name: 'Propriété Caillebotte',
    city: 'Yerres',
    zone: 'Essonne (91)',
    description: "Domaine impressionniste de Gustave Caillebotte. Jardins à l'anglaise, canotage sur l'Yerres, orangerie et kiosque. Cadre de tableau vivant.",
    tags: ['portrait', 'couple', 'nature', 'mode'],
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/81/Propri%C3%A9t%C3%A9_Caillebotte%2C_Yerres.jpg/500px-Propri%C3%A9t%C3%A9_Caillebotte%2C_Yerres.jpg',
    tip: "Le ponton sur la rivière Yerres reproduit exactement les scènes peintes par Caillebotte. Couleurs d'été irisées.",
    access: 'RER D — Yerres, 10 min à pied',
    address: '8 Rue de Concy, 91330 Yerres',
  },
  {
    id: 'cimetiere-russe',
    name: 'Cimetière russe de Sainte-Geneviève-des-Bois',
    city: 'Sainte-Geneviève-des-Bois',
    zone: 'Essonne (91)',
    description: "Cimetière orthodoxe avec coupoles dorées et croix byzantines. Cadre dramatique et solennel, unique en Île-de-France.",
    tags: ['portrait', 'architecture', 'mode'],
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Eglise_notre_dame_de_l_assomption_7.jpg/500px-Eglise_notre_dame_de_l_assomption_7.jpg',
    tip: "Lumière de fin d'après-midi pour les coupoles en contre-jour. Atmosphère hors du temps, très cinématographique.",
    access: "RER C — Sainte-Geneviève-des-Bois, 15 min à pied",
    address: '8 Rue Léo-Lagrange, 91700 Sainte-Geneviève-des-Bois',
  },
  {
    id: 'dourdan',
    name: 'Château de Dourdan & vieille ville',
    city: 'Dourdan',
    zone: 'Essonne (91)',
    description: "Château médiéval du XIIIe avec douves et tours rondes. Vieille ville préservée avec halles et ruelles en pierre.",
    tags: ['portrait', 'couple', 'architecture', 'street'],
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d2/Dourdan_%2891%29_Ch%C3%A2teau_585.jpg/500px-Dourdan_%2891%29_Ch%C3%A2teau_585.jpg',
    tip: "Fossés du château avec herbe haute en été : cadre romantique idéal. Vieille ville quasi vide en semaine.",
    access: 'RER C — Dourdan',
    address: 'Place du Marché, 91410 Dourdan',
  },
  {
    id: 'milly-la-foret',
    name: 'Milly-la-Forêt & Forêt de Milly',
    city: 'Milly-la-Forêt',
    zone: 'Essonne (91)',
    description: "Halle médiévale en charpente du XVe, rues de pavés et forêt accessible à pied. Village carte postale à 50 km de Paris.",
    tags: ['portrait', 'couple', 'architecture', 'nature'],
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/37/La_Halle_de_Milly-la-For%C3%AAt.jpg/500px-La_Halle_de_Milly-la-For%C3%AAt.jpg',
    tip: "Halle médiévale : lumière tamisée à travers les planches en bois, parfaite pour les portraits en clair-obscur. Grotte Jean Cocteau à voir.",
    access: 'Pas de train direct — voiture ou vélo depuis Malesherbes (Transilien)',
    address: 'Place du Marché, 91490 Milly-la-Forêt',
  },
  {
    id: 'montlhery',
    name: 'Tour de Montlhéry',
    city: 'Montlhéry',
    zone: 'Essonne (91)',
    description: "Donjon médiéval du XIe sur une butte avec vue panoramique à 360° sur la plaine de Beauce et l'Île-de-France.",
    tags: ['portrait', 'architecture', 'nature'],
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/97/Ch%C3%A2teau_de_la_Souche_%28Montlh%C3%A9ry%29_mars_2022_6.jpg/500px-Ch%C3%A2teau_de_la_Souche_%28Montlh%C3%A9ry%29_mars_2022_6.jpg',
    tip: "Vue dégagée sur Paris par temps clair. Ruines romantiques pour des portraits à contre-jour en fin de journée.",
    access: 'RER C — Linas — Montlhéry, 20 min à pied',
    address: 'Rue du Château de la Souche, 91310 Montlhéry',
  },
  {
    id: 'etampes',
    name: 'Étampes — Tours médiévales',
    city: 'Étampes',
    zone: 'Essonne (91)',
    description: "Ville médiévale exceptionnellement préservée avec 4 tours en ruines, ruelles pavées et collégiales. Ambiance Game of Thrones.",
    tags: ['portrait', 'couple', 'architecture', 'street'],
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9d/France_Essonne_Etampes_Hotel_de_Ville_02.jpg/500px-France_Essonne_Etampes_Hotel_de_Ville_02.jpg',
    tip: "Tour Guinette et ses abords pour des portraits de pierres anciennes. Ruelle des Juifs très photogénique.",
    access: 'RER C — Étampes',
    address: 'Place Saint-Gilles, 91150 Étampes',
  },
  {
    id: 'cathedrale-evry',
    name: 'Cathédrale de la Résurrection',
    city: 'Évry-Courcouronnes',
    zone: 'Essonne (91)',
    description: "Cathédrale circulaire contemporaine en briques, couverte d'arbres sur le toit. Architecture unique conçue par Mario Botta.",
    tags: ['portrait', 'mode', 'architecture'],
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/46/1_Evry_Cathedral.jpg/500px-1_Evry_Cathedral.jpg',
    tip: "Façade de briques rouges et cylindre végétalisé en surplomb : contraste saisissant pour des portraits mode.",
    access: 'RER D — Évry-Courcouronnes, 5 min à pied',
    address: "1 Rue de l'Abondance, 91000 Évry-Courcouronnes",
  },
  {
    id: 'bords-yerres',
    name: "Bords de l'Yerres",
    city: 'Brunoy / Crosne',
    zone: 'Essonne (91)',
    description: "Rivière calme avec guinguettes, bords ombragés par des saules pleureurs. Ambiance douce et champêtre à 25 min de Paris.",
    tags: ['portrait', 'couple', 'animal', 'nature'],
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/16/L%27Yerres_%C3%A0_Montgeron.jpg/500px-L%27Yerres_%C3%A0_Montgeron.jpg',
    tip: "Saules pleureurs sur les berges : rideaux naturels parfaits pour encadrer des portraits. Lumière verte très douce en été.",
    access: 'RER D — Brunoy',
    address: "Quai de l'Yerres, 91800 Brunoy",
  },
  {
    id: 'courson',
    name: 'Domaine de Courson',
    city: 'Courson-Monteloup',
    zone: 'Essonne (91)',
    description: "Château du XVIIe entouré de jardins paysagers avec pièces d'eau et grands arbres centenaires. Cadre aristocratique hors normes.",
    tags: ['portrait', 'couple', 'mode', 'architecture', 'nature'],
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/Ch%C3%A2teau_de_Courson.jpg/500px-Ch%C3%A2teau_de_Courson.jpg',
    tip: "Journées des Plantes au printemps et automne : accès ouvert. Allées d'arbres centenaires spectaculaires.",
    access: 'Voiture depuis Paris — 45 min (pas de transport direct)',
    address: 'Route de Rochefort, 91680 Courson-Monteloup',
  },
  {
    id: 'plaine-beauce',
    name: 'Champs de tournesols & blé',
    city: 'Étréchy / Méréville',
    zone: 'Essonne (91)',
    description: "Plaines agricoles à perte de vue. Tournesols en juillet, blé doré en juin, coquelicots en mai. Grands espaces et ciel immense.",
    tags: ['portrait', 'couple', 'nature'],
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/be/Plaine_de_Darvault_-_01.JPG/500px-Plaine_de_Darvault_-_01.JPG',
    tip: "Mi-juillet pour les tournesols, fin juin pour le blé doré. Lumière rasante à 19h en été. Venir en semaine pour éviter les curieux.",
    access: 'RER C — Étréchy + vélo ou voiture',
    address: 'Plaine de la Beauce, 91580 Étréchy',
  },

  // ─── SEINE-SAINT-DENIS (93) ───────────────────────────────────────────────
  {
    id: 'saint-denis',
    name: 'Basilique de Saint-Denis',
    city: 'Saint-Denis',
    zone: 'Seine-Saint-Denis (93)',
    description: "Cathédrale gothique monumentale, nécropole des rois de France. Architecture imposante et lumière divine.",
    tags: ['portrait', 'architecture', 'mode'],
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Basilica_of_Saint_Denis%2C_Paris%2C_France.JPG/500px-Basilica_of_Saint_Denis%2C_Paris%2C_France.JPG',
    tip: "Parvis et façade gothique pour des portraits architecturaux puissants. Intérieur très lumineux en mi-journée.",
    access: 'M° Basilique de Saint-Denis',
    address: "1 Rue de la Légion d'Honneur, 93200 Saint-Denis",
  },
  {
    id: 'canal-ourcq',
    name: "Canal de l'Ourcq — Street Art",
    city: 'Pantin / Aubervilliers',
    zone: 'Seine-Saint-Denis (93)',
    description: "Quartier en pleine gentrification. Street art monumental, entrepôts réhabilités et canal. Ambiance brute et créative unique.",
    tags: ['portrait', 'mode', 'street', 'architecture'],
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/06/Pantin.Quai_de_l%27Ourcq.jpg/500px-Pantin.Quai_de_l%27Ourcq.jpg',
    tip: "Abords de la MK2 Quai de Loire pour un mix urbain/eau. Fresques géantes côté Pantin.",
    access: 'M° Aubervilliers — Pantin — Quatre Chemins',
    address: "Quai de l'Ourcq, 93500 Pantin",
  },
  {
    id: 'noisy-le-grand',
    name: 'Les Arènes de Picasso',
    city: 'Noisy-le-Grand',
    zone: 'Seine-Saint-Denis (93)',
    description: "Ensemble architectural post-moderne (1985) aux formes circulaires organiques évoquant des amphithéâtres romains. Béton brut et courbes monumentales pour un style urbain radical.",
    tags: ['portrait', 'mode', 'architecture'],
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b3/Arenes_Picasso_Noisy-Le-Grand.JPG/500px-Arenes_Picasso_Noisy-Le-Grand.JPG',
    tip: "Courbes des façades pour des reflets et déformations très graphiques. Heure bleue pour les lumières des appartements en fond.",
    access: "RER A — Noisy-le-Grand — Mont d'Est",
    address: 'Place Pablo Picasso, 93160 Noisy-le-Grand',
  },
  {
    id: 'montreuil',
    name: 'Murs à Pêches & Street Art',
    city: 'Montreuil',
    zone: 'Seine-Saint-Denis (93)',
    description: "Anciens murs de cultures maraîchères en pierres meulières, désormais recouverts de fresques et street art. Jardin secret urbain unique en Île-de-France.",
    tags: ['portrait', 'mode', 'street', 'nature'],
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/eb/Montreuil-murs-a-peches-01.jpg/500px-Montreuil-murs-a-peches-01.jpg',
    tip: "Murs de pierres meulières et végétation sauvage : contraste parfait pour les portraits mode. Fresques géantes en arrière-plan.",
    access: "M° Robespierre ou Croix de Chavaux",
    address: 'Rue Louis Rolland, 93100 Montreuil',
  },
  {
    id: 'stade-de-france',
    name: 'Abords du Stade de France',
    city: 'Saint-Denis',
    zone: 'Seine-Saint-Denis (93)',
    description: "Architecture monumentale et esplanade industrielle. Lignes épurées et béton brut pour un style urbain marqué.",
    tags: ['portrait', 'mode', 'architecture'],
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Stade_de_france.jpg/500px-Stade_de_france.jpg',
    tip: "Heure bleue pour les lumières du stade en fond. Structures métalliques et passerelles très graphiques.",
    access: 'M° ou RER D — Stade de France — Saint-Denis',
    address: 'Rue Francis de Pressensé, 93210 Saint-Denis',
  },
];
